version: '3.8'
services:
  webapp:
    image: openjdk:8-alpine
    restart: always
    ports:
      - 3000:8080
    networks:
      - qcell
    environment:
      - MONGO_DB_HOSTNAME=mongodb
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=dev@123
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ebsvolume:/data/db
    networks:
      - qcell
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=dev@123
volumes:
 ebsvolume:
    external: true
networks:
  qcell:
    external: true
